apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxv1
  namespace: pg
spec:
  selector:
    matchLabels:
      app: nginxv1
  template:
    metadata:
      labels:
        ingress: traefik
        app: nginxv1
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:  ["/bin/sh", "-c", "echo Hello v1 > /usr/share/nginx/html/index.html"]
          ports:
            - containerPort: 80
              name: nginxv1

---
apiVersion: v1
kind: Service
metadata:
  name: nginxv1
  namespace: pg
spec:
  selector:
    app: nginxv1
    #ingress: traefik
  ports:
    - name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
  namespace: pg
spec:
  rules:
    - host: traefik.2pg.cn
      http:
        paths:
          - path: /bar
            pathType: Exact
            backend:
              service:
                name:  nginxv1
                port:
                  number: 80
          - path: /foo
            pathType: Exact
            backend:
              service:
                name:  nginxv1
                port:
                  number: 80